### PR TITLE
fixing dropdown menu if enable

### PR DESCRIPTION
**Pull request by Allamaris0**
changed navigation.html.twig and main.css

### CODE REVIEW

**Review by adeliktas — APPROVED** [review]
fixed my issue https://github.com/hughbris/grav-theme-minimaxing/issues/12
works fine

**Comment by adeliktas** [comment]
if the element in the dropdown menu has a bigger length the menu bar gets shifted to the left overlapping the website logo(website name).

**Comment by adeliktas** [comment]
There is a issue with the length of the li item/parent page adjusting to the length of the sub page which pushes the list of pages to the left, causing to overlap the website logo.
https://github.com/hughbris/grav-theme-minimaxing/issues/12
@Allamaris0 you have solved that issue as well thanks, pls add the navigation.html.twig from your fork to the commit

**Comment by Allamaris0** [comment]
> There is a issue with the length of the li item/parent page adjusting to the length of the sub page which pushes the list of pages to the left, causing to overlap the website logo.
> #12
> @Allamaris0 you have solved that issue as well thanks, pls add the navigation.html.twig from your fork to the commit

I made 'Pull request' but it hasn't still been approved by author (hughbris).

**Review by adeliktas — APPROVED** [review]

**Review by adeliktas — APPROVED** [review]

**Comment by adeliktas** [comment]
> 
> 
> > There is a issue with the length of the li item/parent page adjusting to the length of the sub page which pushes the list of pages to the left, causing to overlap the website logo.
> > #12
> > @Allamaris0 you have solved that issue as well thanks, pls add the navigation.html.twig from your fork to the commit
> 
> I made 'Pull request' but it hasn't still been approved by author (hughbris).

ah my bad the commit already contains both files needed.
You have solved the Issue mentioned above completely. Thanks again.

Would you mind also taking a look at this Issue as well? https://github.com/hughbris/grav-theme-minimaxing/issues/13

**Review by hughbris — COMMENTED** [review]
Hi - thank you for this, I am extremely late to respond and review.

I made some commits today that make it hard to know how I can incorporate your changes, even though I copied some parts from them. I fixed the limitation where `custom.css` was not being included, so I want to keep any extensions to the source theme in that file. That made it difficult to bring in your changes. For the navigation template,I made my edits according to the previous template design, which supports more levels of nesting (in theory, with styling).

So I'm not sure if there is some backdoor way to incorporate a small piece of this PR so that you are properly credited as a collaborator in this repo. It seems right if I can. Gonna research and think on it.

**Pull request merged**
